### ISSUE TITLE
TSX files do not have icons.

### ISSUE THREAD

**Issue by HTempleman** [domtronn/all-the-icons.el#164]
First off, thanks to everyone who has contributed to this fantastic collection of icons!

For those of us who enjoy working with react in typescript, it would be pleasant to have a correspondent icon for the many .tsx files that are created along the way!

**Comment by HTempleman** [comment]
Closing because issues are resolved by PR #165.

**Comment by Ailrun** [comment]
It looks like it's still not listed in `all-the-icons-icon-alist`.

**Comment by atimchenko92** [comment]
> 
> 
> It looks like it's still not listed in `all-the-icons-icon-alist`.

I second that:
![grafik](https://user-images.githubusercontent.com/9789061/94436053-3e7f7b00-019c-11eb-88e6-bf9af2898e1c.png)

**Comment by mohkale** [comment]
Yep, this is definitely still an issue. In the meantime this should fix the issue.

```lisp
(setcar (assoc "\\.ts$" all-the-icons-icon-alist) (rx (or ".ts" ".tsx") eol))
(setcar (assoc "\\.js$" all-the-icons-icon-alist) (rx (or ".js" ".jsx") eol))
```

**Comment by wyuenho** [comment]
Or just update all-the-icons

**Comment by mohkale** [comment]
Oh wow, @wyuenho is right. `tsx` support was added a [few days ago](https://github.com/domtronn/all-the-icons.el/commit/5225379054caba5e31f099d0aa2fe890039e7f99), my bad :sweat:. And `jsx` has been around for like 4 years.
